# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.live_data_data_dewpoint import LiveDataDataDewpoint  # noqa: F401,E501
from swagger_server.models.live_data_data_temperature import LiveDataDataTemperature  # noqa: F401,E501
from swagger_server import util


class LiveDataData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, temperature: LiveDataDataTemperature=None, dewpoint: LiveDataDataDewpoint=None):  # noqa: E501
        """LiveDataData - a model defined in Swagger

        :param temperature: The temperature of this LiveDataData.  # noqa: E501
        :type temperature: LiveDataDataTemperature
        :param dewpoint: The dewpoint of this LiveDataData.  # noqa: E501
        :type dewpoint: LiveDataDataDewpoint
        """
        self.swagger_types = {
            'temperature': LiveDataDataTemperature,
            'dewpoint': LiveDataDataDewpoint
        }

        self.attribute_map = {
            'temperature': 'temperature',
            'dewpoint': 'dewpoint'
        }
        self._temperature = temperature
        self._dewpoint = dewpoint

    @classmethod
    def from_dict(cls, dikt) -> 'LiveDataData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LiveData_data of this LiveDataData.  # noqa: E501
        :rtype: LiveDataData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def temperature(self) -> LiveDataDataTemperature:
        """Gets the temperature of this LiveDataData.


        :return: The temperature of this LiveDataData.
        :rtype: LiveDataDataTemperature
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: LiveDataDataTemperature):
        """Sets the temperature of this LiveDataData.


        :param temperature: The temperature of this LiveDataData.
        :type temperature: LiveDataDataTemperature
        """

        self._temperature = temperature

    @property
    def dewpoint(self) -> LiveDataDataDewpoint:
        """Gets the dewpoint of this LiveDataData.


        :return: The dewpoint of this LiveDataData.
        :rtype: LiveDataDataDewpoint
        """
        return self._dewpoint

    @dewpoint.setter
    def dewpoint(self, dewpoint: LiveDataDataDewpoint):
        """Sets the dewpoint of this LiveDataData.


        :param dewpoint: The dewpoint of this LiveDataData.
        :type dewpoint: LiveDataDataDewpoint
        """

        self._dewpoint = dewpoint
