# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.live_data_data import LiveDataData  # noqa: F401,E501
from swagger_server import util


class LiveData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, site_id: str=None, site_human_readable: str=None, _datetime: date=None, data: LiveDataData=None):  # noqa: E501
        """LiveData - a model defined in Swagger

        :param site_id: The site_id of this LiveData.  # noqa: E501
        :type site_id: str
        :param site_human_readable: The site_human_readable of this LiveData.  # noqa: E501
        :type site_human_readable: str
        :param _datetime: The _datetime of this LiveData.  # noqa: E501
        :type _datetime: date
        :param data: The data of this LiveData.  # noqa: E501
        :type data: LiveDataData
        """
        self.swagger_types = {
            'site_id': str,
            'site_human_readable': str,
            '_datetime': date,
            'data': LiveDataData
        }

        self.attribute_map = {
            'site_id': 'siteID',
            'site_human_readable': 'siteHumanReadable',
            '_datetime': 'datetime',
            'data': 'data'
        }
        self._site_id = site_id
        self._site_human_readable = site_human_readable
        self.__datetime = _datetime
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'LiveData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LiveData of this LiveData.  # noqa: E501
        :rtype: LiveData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def site_id(self) -> str:
        """Gets the site_id of this LiveData.


        :return: The site_id of this LiveData.
        :rtype: str
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id: str):
        """Sets the site_id of this LiveData.


        :param site_id: The site_id of this LiveData.
        :type site_id: str
        """

        self._site_id = site_id

    @property
    def site_human_readable(self) -> str:
        """Gets the site_human_readable of this LiveData.


        :return: The site_human_readable of this LiveData.
        :rtype: str
        """
        return self._site_human_readable

    @site_human_readable.setter
    def site_human_readable(self, site_human_readable: str):
        """Sets the site_human_readable of this LiveData.


        :param site_human_readable: The site_human_readable of this LiveData.
        :type site_human_readable: str
        """

        self._site_human_readable = site_human_readable

    @property
    def _datetime(self) -> date:
        """Gets the _datetime of this LiveData.


        :return: The _datetime of this LiveData.
        :rtype: date
        """
        return self.__datetime

    @_datetime.setter
    def _datetime(self, _datetime: date):
        """Sets the _datetime of this LiveData.


        :param _datetime: The _datetime of this LiveData.
        :type _datetime: date
        """

        self.__datetime = _datetime

    @property
    def data(self) -> LiveDataData:
        """Gets the data of this LiveData.


        :return: The data of this LiveData.
        :rtype: LiveDataData
        """
        return self._data

    @data.setter
    def data(self, data: LiveDataData):
        """Sets the data of this LiveData.


        :param data: The data of this LiveData.
        :type data: LiveDataData
        """

        self._data = data
