# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LiveDataDataTemperature(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, value: float=None, unit: str=None):  # noqa: E501
        """LiveDataDataTemperature - a model defined in Swagger

        :param value: The value of this LiveDataDataTemperature.  # noqa: E501
        :type value: float
        :param unit: The unit of this LiveDataDataTemperature.  # noqa: E501
        :type unit: str
        """
        self.swagger_types = {
            'value': float,
            'unit': str
        }

        self.attribute_map = {
            'value': 'value',
            'unit': 'unit'
        }
        self._value = value
        self._unit = unit

    @classmethod
    def from_dict(cls, dikt) -> 'LiveDataDataTemperature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LiveData_data_temperature of this LiveDataDataTemperature.  # noqa: E501
        :rtype: LiveDataDataTemperature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> float:
        """Gets the value of this LiveDataDataTemperature.


        :return: The value of this LiveDataDataTemperature.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this LiveDataDataTemperature.


        :param value: The value of this LiveDataDataTemperature.
        :type value: float
        """

        self._value = value

    @property
    def unit(self) -> str:
        """Gets the unit of this LiveDataDataTemperature.


        :return: The unit of this LiveDataDataTemperature.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this LiveDataDataTemperature.


        :param unit: The unit of this LiveDataDataTemperature.
        :type unit: str
        """

        self._unit = unit
