# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SiteListInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, site_id: str=None, site_human_readable: str=None):  # noqa: E501
        """SiteListInner - a model defined in Swagger

        :param site_id: The site_id of this SiteListInner.  # noqa: E501
        :type site_id: str
        :param site_human_readable: The site_human_readable of this SiteListInner.  # noqa: E501
        :type site_human_readable: str
        """
        self.swagger_types = {
            'site_id': str,
            'site_human_readable': str
        }

        self.attribute_map = {
            'site_id': 'siteID',
            'site_human_readable': 'siteHumanReadable'
        }
        self._site_id = site_id
        self._site_human_readable = site_human_readable

    @classmethod
    def from_dict(cls, dikt) -> 'SiteListInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SiteList_inner of this SiteListInner.  # noqa: E501
        :rtype: SiteListInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def site_id(self) -> str:
        """Gets the site_id of this SiteListInner.


        :return: The site_id of this SiteListInner.
        :rtype: str
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id: str):
        """Sets the site_id of this SiteListInner.


        :param site_id: The site_id of this SiteListInner.
        :type site_id: str
        """

        self._site_id = site_id

    @property
    def site_human_readable(self) -> str:
        """Gets the site_human_readable of this SiteListInner.


        :return: The site_human_readable of this SiteListInner.
        :rtype: str
        """
        return self._site_human_readable

    @site_human_readable.setter
    def site_human_readable(self, site_human_readable: str):
        """Sets the site_human_readable of this SiteListInner.


        :param site_human_readable: The site_human_readable of this SiteListInner.
        :type site_human_readable: str
        """

        self._site_human_readable = site_human_readable
