# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SiteDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, site_id: str=None, site_human_readable: str=None, description: str=None):  # noqa: E501
        """SiteDetails - a model defined in Swagger

        :param site_id: The site_id of this SiteDetails.  # noqa: E501
        :type site_id: str
        :param site_human_readable: The site_human_readable of this SiteDetails.  # noqa: E501
        :type site_human_readable: str
        :param description: The description of this SiteDetails.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'site_id': str,
            'site_human_readable': str,
            'description': str
        }

        self.attribute_map = {
            'site_id': 'siteID',
            'site_human_readable': 'siteHumanReadable',
            'description': 'description'
        }
        self._site_id = site_id
        self._site_human_readable = site_human_readable
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'SiteDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SiteDetails of this SiteDetails.  # noqa: E501
        :rtype: SiteDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def site_id(self) -> str:
        """Gets the site_id of this SiteDetails.


        :return: The site_id of this SiteDetails.
        :rtype: str
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id: str):
        """Sets the site_id of this SiteDetails.


        :param site_id: The site_id of this SiteDetails.
        :type site_id: str
        """

        self._site_id = site_id

    @property
    def site_human_readable(self) -> str:
        """Gets the site_human_readable of this SiteDetails.


        :return: The site_human_readable of this SiteDetails.
        :rtype: str
        """
        return self._site_human_readable

    @site_human_readable.setter
    def site_human_readable(self, site_human_readable: str):
        """Sets the site_human_readable of this SiteDetails.


        :param site_human_readable: The site_human_readable of this SiteDetails.
        :type site_human_readable: str
        """

        self._site_human_readable = site_human_readable

    @property
    def description(self) -> str:
        """Gets the description of this SiteDetails.


        :return: The description of this SiteDetails.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this SiteDetails.


        :param description: The description of this SiteDetails.
        :type description: str
        """

        self._description = description
