# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VisualizationListInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, visualisation_id: int=None, site_id: str=None, instrument_id: str=None, product_id: str=None, aggregations: List=None, site_human_readable: str=None, instrument_human_readable: str=None, product_human_readable: str=None):  # noqa: E501
        """VisualizationListInner - a model defined in Swagger

        :param visualisation_id: The visualisation_id of this VisualizationListInner.  # noqa: E501
        :type visualisation_id: int
        :param site_id: The site_id of this VisualizationListInner.  # noqa: E501
        :type site_id: str
        :param instrument_id: The instrument_id of this VisualizationListInner.  # noqa: E501
        :type instrument_id: str
        :param product_id: The product_id of this VisualizationListInner.  # noqa: E501
        :type product_id: str
        :param aggregations: The aggregations of this VisualizationListInner.  # noqa: E501
        :type aggregations: List
        :param site_human_readable: The site_human_readable of this VisualizationListInner.  # noqa: E501
        :type site_human_readable: str
        :param instrument_human_readable: The instrument_human_readable of this VisualizationListInner.  # noqa: E501
        :type instrument_human_readable: str
        :param product_human_readable: The product_human_readable of this VisualizationListInner.  # noqa: E501
        :type product_human_readable: str
        """
        self.swagger_types = {
            'visualisation_id': int,
            'site_id': str,
            'instrument_id': str,
            'product_id': str,
            'aggregations': List,
            'site_human_readable': str,
            'instrument_human_readable': str,
            'product_human_readable': str
        }

        self.attribute_map = {
            'visualisation_id': 'visualisationID',
            'site_id': 'siteID',
            'instrument_id': 'instrumentID',
            'product_id': 'productID',
            'aggregations': 'aggregations',
            'site_human_readable': 'siteHumanReadable',
            'instrument_human_readable': 'instrumentHumanReadable',
            'product_human_readable': 'productHumanReadable'
        }
        self._visualisation_id = visualisation_id
        self._site_id = site_id
        self._instrument_id = instrument_id
        self._product_id = product_id
        self._aggregations = aggregations
        self._site_human_readable = site_human_readable
        self._instrument_human_readable = instrument_human_readable
        self._product_human_readable = product_human_readable

    @classmethod
    def from_dict(cls, dikt) -> 'VisualizationListInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VisualizationList_inner of this VisualizationListInner.  # noqa: E501
        :rtype: VisualizationListInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def visualisation_id(self) -> int:
        """Gets the visualisation_id of this VisualizationListInner.


        :return: The visualisation_id of this VisualizationListInner.
        :rtype: int
        """
        return self._visualisation_id

    @visualisation_id.setter
    def visualisation_id(self, visualisation_id: int):
        """Sets the visualisation_id of this VisualizationListInner.


        :param visualisation_id: The visualisation_id of this VisualizationListInner.
        :type visualisation_id: int
        """

        self._visualisation_id = visualisation_id

    @property
    def site_id(self) -> str:
        """Gets the site_id of this VisualizationListInner.


        :return: The site_id of this VisualizationListInner.
        :rtype: str
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id: str):
        """Sets the site_id of this VisualizationListInner.


        :param site_id: The site_id of this VisualizationListInner.
        :type site_id: str
        """

        self._site_id = site_id

    @property
    def instrument_id(self) -> str:
        """Gets the instrument_id of this VisualizationListInner.


        :return: The instrument_id of this VisualizationListInner.
        :rtype: str
        """
        return self._instrument_id

    @instrument_id.setter
    def instrument_id(self, instrument_id: str):
        """Sets the instrument_id of this VisualizationListInner.


        :param instrument_id: The instrument_id of this VisualizationListInner.
        :type instrument_id: str
        """

        self._instrument_id = instrument_id

    @property
    def product_id(self) -> str:
        """Gets the product_id of this VisualizationListInner.


        :return: The product_id of this VisualizationListInner.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: str):
        """Sets the product_id of this VisualizationListInner.


        :param product_id: The product_id of this VisualizationListInner.
        :type product_id: str
        """

        self._product_id = product_id

    @property
    def aggregations(self) -> List:
        """Gets the aggregations of this VisualizationListInner.


        :return: The aggregations of this VisualizationListInner.
        :rtype: List
        """
        return self._aggregations

    @aggregations.setter
    def aggregations(self, aggregations: List):
        """Sets the aggregations of this VisualizationListInner.


        :param aggregations: The aggregations of this VisualizationListInner.
        :type aggregations: List
        """

        self._aggregations = aggregations

    @property
    def site_human_readable(self) -> str:
        """Gets the site_human_readable of this VisualizationListInner.


        :return: The site_human_readable of this VisualizationListInner.
        :rtype: str
        """
        return self._site_human_readable

    @site_human_readable.setter
    def site_human_readable(self, site_human_readable: str):
        """Sets the site_human_readable of this VisualizationListInner.


        :param site_human_readable: The site_human_readable of this VisualizationListInner.
        :type site_human_readable: str
        """

        self._site_human_readable = site_human_readable

    @property
    def instrument_human_readable(self) -> str:
        """Gets the instrument_human_readable of this VisualizationListInner.


        :return: The instrument_human_readable of this VisualizationListInner.
        :rtype: str
        """
        return self._instrument_human_readable

    @instrument_human_readable.setter
    def instrument_human_readable(self, instrument_human_readable: str):
        """Sets the instrument_human_readable of this VisualizationListInner.


        :param instrument_human_readable: The instrument_human_readable of this VisualizationListInner.
        :type instrument_human_readable: str
        """

        self._instrument_human_readable = instrument_human_readable

    @property
    def product_human_readable(self) -> str:
        """Gets the product_human_readable of this VisualizationListInner.


        :return: The product_human_readable of this VisualizationListInner.
        :rtype: str
        """
        return self._product_human_readable

    @product_human_readable.setter
    def product_human_readable(self, product_human_readable: str):
        """Sets the product_human_readable of this VisualizationListInner.


        :param product_human_readable: The product_human_readable of this VisualizationListInner.
        :type product_human_readable: str
        """

        self._product_human_readable = product_human_readable
