# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Visualisation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, visualisation_id: int=None, site_id: str=None, instrument_id: str=None, product_id: str=None, site_human_readable: str=None, instrument_human_readable: str=None, product_human_readable: str=None, _datetime: date=None, base_url: str=None, visualisation_file_name: str=None, full_url: str=None):  # noqa: E501
        """Visualisation - a model defined in Swagger

        :param visualisation_id: The visualisation_id of this Visualisation.  # noqa: E501
        :type visualisation_id: int
        :param site_id: The site_id of this Visualisation.  # noqa: E501
        :type site_id: str
        :param instrument_id: The instrument_id of this Visualisation.  # noqa: E501
        :type instrument_id: str
        :param product_id: The product_id of this Visualisation.  # noqa: E501
        :type product_id: str
        :param site_human_readable: The site_human_readable of this Visualisation.  # noqa: E501
        :type site_human_readable: str
        :param instrument_human_readable: The instrument_human_readable of this Visualisation.  # noqa: E501
        :type instrument_human_readable: str
        :param product_human_readable: The product_human_readable of this Visualisation.  # noqa: E501
        :type product_human_readable: str
        :param _datetime: The _datetime of this Visualisation.  # noqa: E501
        :type _datetime: date
        :param base_url: The base_url of this Visualisation.  # noqa: E501
        :type base_url: str
        :param visualisation_file_name: The visualisation_file_name of this Visualisation.  # noqa: E501
        :type visualisation_file_name: str
        :param full_url: The full_url of this Visualisation.  # noqa: E501
        :type full_url: str
        """
        self.swagger_types = {
            'visualisation_id': int,
            'site_id': str,
            'instrument_id': str,
            'product_id': str,
            'site_human_readable': str,
            'instrument_human_readable': str,
            'product_human_readable': str,
            '_datetime': date,
            'base_url': str,
            'visualisation_file_name': str,
            'full_url': str
        }

        self.attribute_map = {
            'visualisation_id': 'visualisationID',
            'site_id': 'siteID',
            'instrument_id': 'instrumentID',
            'product_id': 'productID',
            'site_human_readable': 'siteHumanReadable',
            'instrument_human_readable': 'instrumentHumanReadable',
            'product_human_readable': 'productHumanReadable',
            '_datetime': 'datetime',
            'base_url': 'baseURL',
            'visualisation_file_name': 'visualisationFileName',
            'full_url': 'fullURL'
        }
        self._visualisation_id = visualisation_id
        self._site_id = site_id
        self._instrument_id = instrument_id
        self._product_id = product_id
        self._site_human_readable = site_human_readable
        self._instrument_human_readable = instrument_human_readable
        self._product_human_readable = product_human_readable
        self.__datetime = _datetime
        self._base_url = base_url
        self._visualisation_file_name = visualisation_file_name
        self._full_url = full_url

    @classmethod
    def from_dict(cls, dikt) -> 'Visualisation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Visualisation of this Visualisation.  # noqa: E501
        :rtype: Visualisation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def visualisation_id(self) -> int:
        """Gets the visualisation_id of this Visualisation.


        :return: The visualisation_id of this Visualisation.
        :rtype: int
        """
        return self._visualisation_id

    @visualisation_id.setter
    def visualisation_id(self, visualisation_id: int):
        """Sets the visualisation_id of this Visualisation.


        :param visualisation_id: The visualisation_id of this Visualisation.
        :type visualisation_id: int
        """

        self._visualisation_id = visualisation_id

    @property
    def site_id(self) -> str:
        """Gets the site_id of this Visualisation.


        :return: The site_id of this Visualisation.
        :rtype: str
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id: str):
        """Sets the site_id of this Visualisation.


        :param site_id: The site_id of this Visualisation.
        :type site_id: str
        """

        self._site_id = site_id

    @property
    def instrument_id(self) -> str:
        """Gets the instrument_id of this Visualisation.


        :return: The instrument_id of this Visualisation.
        :rtype: str
        """
        return self._instrument_id

    @instrument_id.setter
    def instrument_id(self, instrument_id: str):
        """Sets the instrument_id of this Visualisation.


        :param instrument_id: The instrument_id of this Visualisation.
        :type instrument_id: str
        """

        self._instrument_id = instrument_id

    @property
    def product_id(self) -> str:
        """Gets the product_id of this Visualisation.


        :return: The product_id of this Visualisation.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: str):
        """Sets the product_id of this Visualisation.


        :param product_id: The product_id of this Visualisation.
        :type product_id: str
        """

        self._product_id = product_id

    @property
    def site_human_readable(self) -> str:
        """Gets the site_human_readable of this Visualisation.


        :return: The site_human_readable of this Visualisation.
        :rtype: str
        """
        return self._site_human_readable

    @site_human_readable.setter
    def site_human_readable(self, site_human_readable: str):
        """Sets the site_human_readable of this Visualisation.


        :param site_human_readable: The site_human_readable of this Visualisation.
        :type site_human_readable: str
        """

        self._site_human_readable = site_human_readable

    @property
    def instrument_human_readable(self) -> str:
        """Gets the instrument_human_readable of this Visualisation.


        :return: The instrument_human_readable of this Visualisation.
        :rtype: str
        """
        return self._instrument_human_readable

    @instrument_human_readable.setter
    def instrument_human_readable(self, instrument_human_readable: str):
        """Sets the instrument_human_readable of this Visualisation.


        :param instrument_human_readable: The instrument_human_readable of this Visualisation.
        :type instrument_human_readable: str
        """

        self._instrument_human_readable = instrument_human_readable

    @property
    def product_human_readable(self) -> str:
        """Gets the product_human_readable of this Visualisation.


        :return: The product_human_readable of this Visualisation.
        :rtype: str
        """
        return self._product_human_readable

    @product_human_readable.setter
    def product_human_readable(self, product_human_readable: str):
        """Sets the product_human_readable of this Visualisation.


        :param product_human_readable: The product_human_readable of this Visualisation.
        :type product_human_readable: str
        """

        self._product_human_readable = product_human_readable

    @property
    def _datetime(self) -> date:
        """Gets the _datetime of this Visualisation.


        :return: The _datetime of this Visualisation.
        :rtype: date
        """
        return self.__datetime

    @_datetime.setter
    def _datetime(self, _datetime: date):
        """Sets the _datetime of this Visualisation.


        :param _datetime: The _datetime of this Visualisation.
        :type _datetime: date
        """

        self.__datetime = _datetime

    @property
    def base_url(self) -> str:
        """Gets the base_url of this Visualisation.


        :return: The base_url of this Visualisation.
        :rtype: str
        """
        return self._base_url

    @base_url.setter
    def base_url(self, base_url: str):
        """Sets the base_url of this Visualisation.


        :param base_url: The base_url of this Visualisation.
        :type base_url: str
        """

        self._base_url = base_url

    @property
    def visualisation_file_name(self) -> str:
        """Gets the visualisation_file_name of this Visualisation.


        :return: The visualisation_file_name of this Visualisation.
        :rtype: str
        """
        return self._visualisation_file_name

    @visualisation_file_name.setter
    def visualisation_file_name(self, visualisation_file_name: str):
        """Sets the visualisation_file_name of this Visualisation.


        :param visualisation_file_name: The visualisation_file_name of this Visualisation.
        :type visualisation_file_name: str
        """

        self._visualisation_file_name = visualisation_file_name

    @property
    def full_url(self) -> str:
        """Gets the full_url of this Visualisation.


        :return: The full_url of this Visualisation.
        :rtype: str
        """
        return self._full_url

    @full_url.setter
    def full_url(self, full_url: str):
        """Sets the full_url of this Visualisation.


        :param full_url: The full_url of this Visualisation.
        :type full_url: str
        """

        self._full_url = full_url
